##########################################################################
# 部署配置文件(base)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # nginx
  nginx:
    image: ${IMAGE_NGINX}
    container_name: "nginx.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "nginx.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volume/nginx/conf/http.d:/etc/nginx/http.d:ro
      - ./volume/nginx/data:/usr/share/nginx/html:ro
    network_mode: "host"
    extra_hosts:
      - "nginx.${PRODUCT_NAME}.${COMPANY_NAME}:${HOST_IP}"
